In [2]:
%matplotlib inline
import numpy as np
import numpy.random
import matplotlib.pyplot as plt

In [10]:
a.unique

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

delete by indices

In [24]:
a=np.arange(5,10)

index=[0,1]
a=np.delete(a, index)
a

array([7, 8, 9])

delete by values

In [39]:
a=np.arange(5,10)

values=[5,6]
np.where(values)
#a=np.delete(a, [np.where(v) for v in values])
#a

(array([0, 1]),)

In [53]:
a=np.arange(5,10)
values=[9]
#a.sort()
print np.searchsorted(a, values)
len(a)

[4]


5

In [64]:
a=np.array([1,1,2,3])
a[np.where(a<5)]

array([1, 1, 2, 3])

In [6]:
#http://stackoverflow.com/questions/2272149/round-to-5-or-other-number-in-python
#10 -> 10
#12 -> 10
#13 -> 15
#14 -> 15
#16 -> 15
#18 -> 20
def roundint(x, base=5):
    return int(base * round(float(x)/base))

a=range(20)
map(myround, a)

[0, 0, 0, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10, 15, 15, 15, 15, 15, 20, 20]

In [7]:
%qtconsole